main: compile
	./main.exe

compile:
	g++ main.cpp -o main.exe

fibonacci: compile_fibonacci
	./fib.exe

compile_fibonacci:
	g++ fibonacci.cpp -o fib.exe

map: compile_map
	./map.exe
	
compile_map:
	g++ map.cpp -o map.exe