main: compilemain
	./main.exe

compilemain:
	g++ main.cpp -o main.exe

swap: compileswap
	./swap.exe

compileswap:
	g++ swap.cpp -o swap.exe

sort: compilesort
	./sort.exe

compilesort:
	g++ sort.cpp -o sort.exe