d_array:compile_darray
	./d_array.exe

compile_darray:
	g++ dynamicarray.cpp -o d_array.exe

linkedlist: compile_ll
	./linkedlist.exe

compile_ll:
	g++ linkedlist.cpp -o linkedlist.exe

dll: compile_dll
	./dll.exe

compile_dll:
	g++ dll.cpp -o dll.exe

queue: compile_queue
	./queue.exe

compile_queue:
	g++ queue.cpp -o queue.exe

stack: compile_stack
	./stack.exe

compile_stack:
	g++ stack.cpp -o stack.exe

clear:
	rm -rf *.exe